#include "../src/testing.hpp"
#include "../.tools/windivert.h"
#include <iostream>
int wmain(int argc,wchar_t** argv){try{if(argc!=2)throw std::runtime_error("Provide DLL");auto dll=LoadLibraryW(argv[1]);if(!dll)throw std::runtime_error("Cannot load WinDivert");auto compile=(decltype(&WinDivertHelperCompileFilter))GetProcAddress(dll,"WinDivertHelperCompileFilter");auto eval=(decltype(&WinDivertHelperEvalFilter))GetProcAddress(dll,"WinDivertHelperEvalFilter");if(!compile||!eval)throw std::runtime_error("Missing filter API");std::vector<std::string> filters;for(unsigned i=0;i<3;i++){auto filter=isolatedFilter(strategyPorts(i));const char* error=nullptr;UINT at=0;if(!compile(filter.c_str(),WINDIVERT_LAYER_NETWORK,nullptr,0,&error,&at))throw std::runtime_error(error?error:"Invalid filter");filters.push_back(filter);}
    struct Packet{WINDIVERT_IPHDR ip;WINDIVERT_TCPHDR tcp;}packet{};packet.ip.Version=4;packet.ip.HdrLength=5;packet.ip.Length=0x2800;packet.ip.TTL=64;packet.ip.Protocol=6;packet.tcp.HdrLength=5;packet.tcp.Syn=1;
    auto htonsLocal=[](unsigned p){return (UINT16)((p>>8)|((p&255)<<8));};int checks=0;
    for(unsigned band=0;band<3;band++)for(bool outbound:{false,true})for(unsigned port:{strategyPorts(band).first,strategyPorts(band).last}){packet.tcp.SrcPort=htonsLocal(outbound?port:443);packet.tcp.DstPort=htonsLocal(outbound?443:port);WINDIVERT_ADDRESS address{};address.Outbound=outbound;address.Layer=WINDIVERT_LAYER_NETWORK;
        for(unsigned filter=0;filter<3;filter++){bool matches=eval(filters[filter].c_str(),&packet,sizeof(packet),&address)!=FALSE;if(matches!=(filter==band))throw std::runtime_error("Cross-strategy packet capture");checks++;}address.Impostor=1;if(eval(filters[band].c_str(),&packet,sizeof(packet),&address))throw std::runtime_error("Captured impostor");address.Impostor=0;address.Loopback=1;if(eval(filters[band].c_str(),&packet,sizeof(packet),&address))throw std::runtime_error("Captured loopback");}
    FreeLibrary(dll);std::cout<<"PASS: official WinDivert DLL compiled 3 filters and verified "<<checks<<" packet routing cases; no driver started\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
