#include "../src/maintenance.hpp"
#include <iostream>
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F fn){bool rejected=false;try{fn();}catch(...){rejected=true;}require(rejected,"Expected rejection");}
int wmain(int argc,wchar_t** argv){try{
    require(argc>=3,"Provide isolated root and process fixture");fs::path root=fs::absolute(argv[1]);fs::create_directories(root);
    auto fixture=root/L"zapret";writeBytes(fixture/L"bin"/L"winws.exe","fixture never executed");fs::create_directories(fixture/L"lists");writeBytes(fixture/L"general.bat","start \"test\" \"%BIN%winws.exe\" --wf-tcp=443\n");
    writeBytes(fixture/L"utils"/L"targets.txt","# comment\nDiscord = \"https://discord.com\"\nDuplicate = \"https://discord.com\"\nPing = \"PING:1.1.1.1\"\nHttp = \"http://discord.com\"\nBad = \"https://user:password@example.com\"\nYouTube = \"https://www.youtube.com\"\nOther = \"https://www.cloudflare.com\"\n");
    auto targets=testTargets(fixture);require(targets.size()==3&&targets[0].group=="Discord"&&targets[1].group=="YouTube","Target parsing/dedup failed");require(testTargets(root/L"missing").size()==6,"Fallback targets missing");
    auto good=[](const char* group,int ms){return Json{{"group",group},{"reachable",true},{"milliseconds",ms}};};
    Json one={{"score",testScore(Json::array({good("Discord",100),good("Other",100)}))}},control={{"score",testScore(Json::array({good("Other",1),good("Other",1),good("Other",1)}))}};
    require(betterTest(one,control),"Control endpoints dominated bypass score");auto fast=one;fast["score"]["milliseconds"]=10;require(betterTest(fast,one)&&!betterTest(one,fast),"Latency tie break failed");
    require(probeTargets(targets,[]{return true;}).empty(),"Cancelled probe made requests");require(probeTargets(targets,[]{throw std::runtime_error("cancel fault");return false;}).empty(),"Cancel callback crashed worker");
    for(size_t i=0;i<128;i++){auto band=strategyPorts(i);require(band.first<=band.last&&band.last<49152,"Test band exceeds reserved range");if(i)require(strategyPorts(i-1).last<band.first,"Test port bands overlap");}rejects([]{strategyPorts(128);});auto isolated=isolatedArguments("\"--wf-tcp=80,443\" \"--wf-udp=443\" \"--filter-tcp=443\" \"--dpi-desync=fake\"",strategyPorts(0));require(isolated.find(L"--wf-tcp=")==std::wstring::npos&&isolated.find(L"--wf-udp=")==std::wstring::npos&&isolated.find(L"--wf-raw=")!=std::wstring::npos&&isolated.find(L"--filter-tcp=443")!=std::wstring::npos,"Isolation retained overlapping filters or lost strategy");
    auto version=inspect(fixture);writeBytes(fixture/L"bin"/L"stun.bin","fake data");writeBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin","old fake");replaceFake(version,"stun.bin",true);require(fileBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin",100)=="fake data"&&fileBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin.before-change",100)=="old fake","Fake replacement lost backup");rejects([&]{replaceFake(version,"../winws.exe",true);});
    HANDLE fixtureHandle=nullptr;DWORD fixtureId=0;{
        TestProcess child(fs::absolute(argv[2]),L"");require(child.running(),"Child not running");auto snap=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W p{sizeof(p)};if(Process32FirstW(snap,&p))do{if(p.th32ParentProcessID==GetCurrentProcessId()&&_wcsicmp(p.szExeFile,L"test_process_fixture.exe")==0){fixtureId=p.th32ProcessID;break;}}while(Process32NextW(snap,&p));CloseHandle(snap);require(fixtureId!=0,"Fixture child missing");fixtureHandle=OpenProcess(SYNCHRONIZE,FALSE,fixtureId);require(fixtureHandle!=nullptr,"Fixture handle missing");
    }require(WaitForSingleObject(fixtureHandle,5000)==WAIT_OBJECT_0,"Job left child running");CloseHandle(fixtureHandle);
    Json report={{"message","fixture"},{"results",Json::array()},{"best",nullptr}};require(testReportText(report).find(L"fixture")!=std::wstring::npos,"Report rendering failed");
    auto existing=serviceState();if(existing.installed&&!existing.owned){auto config=root/L"foreign-service-guard"/L"settings.json";fs::create_directories(config.parent_path());runStrategyTests(config,true,GetCurrentProcessId());auto protectedReport=Json::parse(fileBytes(config.parent_path()/L"test-report.json",65536));require(protectedReport.contains("error")&&protectedReport["results"].empty(),"Foreign service not rejected");auto after=serviceState();require(after.binary==existing.binary&&after.running==existing.running&&after.owned==existing.owned,"Foreign service changed");std::cout<<"PASS: existing foreign service rejected without changing its state\n";}
    if(argc==4&&std::wstring(argv[3])==L"--live"){auto rows=probeTargets(testTargets(root/L"missing"),[]{return false;});require(rows.size()==6,"Live probe missing results");for(auto& row:rows)std::cout<<row["name"]<<": TLS "<<row["reachable"]<<", HTTP "<<row["status"]<<", error "<<row["error"]<<"\n";writeJsonAtomic(root/L"live-report.json",{{"targets",rows}});
        std::vector<std::thread> workers;std::vector<Json> bound(3);for(size_t i=0;i<3;i++)workers.emplace_back([&,i]{bound[i]=probeBoundTargets({targets[0],targets[1],targets[2]},strategyPorts(i),[]{return false;});});for(auto& worker:workers)worker.join();int successful=0;for(size_t i=0;i<bound.size();i++)for(auto& row:bound[i]){std::cout<<"Band "<<i<<": "<<row.dump()<<"\n";require(!row.value("isolation_error",false),"Curl escaped local port range");if(row.value("reachable",false)){successful++;auto port=row.at("local_port").get<unsigned>();require(port>=strategyPorts(i).first&&port<=strategyPorts(i).last,"Wrong local port");}}require(successful>0,"No live bound probes succeeded");writeJsonAtomic(root/L"bound-report.json",bound);
    }
    std::cout<<"PASS: targets, TLS-only selection, ranking, cancellation, fake backups and owned process cleanup\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
