#include "../src/runtime.hpp"
#include <iostream>
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F fn){bool rejected=false;try{fn();}catch(...){rejected=true;}require(rejected,"Expected rejection");}
int wmain(int argc,wchar_t** argv){try{
    require(argc>=3,"Provide isolated root and process fixture");fs::path root=fs::absolute(argv[1]);fs::create_directories(root);
    auto fixture=root/L"zapret";writeBytes(fixture/L"bin"/L"winws.exe","fixture never executed");fs::create_directories(fixture/L"lists");writeBytes(fixture/L"general.bat","start \"test\" \"%BIN%winws.exe\" --wf-tcp=443\n");
    {auto file=root/L"legacy"/L"settings.json";Json legacy={{"schema",1},{"revision",5},{"installs",Json::array()},{"profile",{{"version_id",""},{"strategy",""},{"game_filter",true},{"ipset_mode","loaded"}}}};writeJsonAtomic(file,legacy);auto bytes=fileBytes(file,65536);Store store(file);auto state=store.load();require(gameMode(state.profile)=="all"&&state.profile.tcpPorts=="1024-65535","Legacy migration defaults changed");state=store.setProfile({{"game_mode","udp"},{"tcp_ports","443"},{"udp_ports","27015-27050"}},5,false);require(state.revision==6&&Json::parse(fileBytes(file,65536))["schema"]==2,"Schema2 migration failed");require(fileBytes(fs::path(file.wstring()+L".before-schema2"),65536)==bytes,"Migration backup changed");auto saved=store.load();require(gameMode(saved.profile)=="udp"&&saved.profile.tcpPorts=="443","Extended settings did not persist");}
    {auto hosts=root/L"hosts";std::string user="127.0.0.1 localhost\r\n192.0.2.1 my.example # keep\r\n",source="203.0.113.5 discord.com\n2001:db8::1 github.com\n";writeBytes(hosts,user);auto merged=mergeHosts(user,source);require(merged.find(user)==0&&mergeHosts(merged,source)==merged,"Hosts update not idempotent");rejects([&]{mergeHosts(user,"192.0.2.8 my.example\n");});rejects([&]{mergeHosts(user,"999.2.3.4 bad.example\n");});rejects([&]{withoutManagedHosts("# BEGIN ZapretGUI Flowseal\nuser entry");});changeHosts(hosts,source,false);require(fileBytes(hosts,65536)==merged,"Hosts merge failed");changeHosts(hosts,"",true);require(fileBytes(hosts,65536)==user,"Hosts removal lost user entries");}
    {Profile p{};p.ipset="none";writeBytes(fixture/L"lists"/L"ipset-all.txt.backup","192.0.2.0/24\n");updateIpSet(fixture,p,"203.0.113.0/24\n2001:db8::/32\n");require(fileBytes(fixture/L"lists"/L"ipset-all.txt",65536)=="203.0.113.113/32\n"&&fileBytes(fixture/L"lists"/L"ipset-all.txt.before-update",65536)=="192.0.2.0/24\n","IPSet update changed disabled mode or lost backup");rejects([&]{checkedIpSet("192.0.2.0/33\n");});}
    writeBytes(fixture/L"utils"/L"targets.txt","# comment\nDiscord = \"https://discord.com\"\nDuplicate = \"https://discord.com\"\nPing = \"PING:1.1.1.1\"\nHttp = \"http://discord.com\"\nBad = \"https://user:password@example.com\"\nYouTube = \"https://www.youtube.com\"\nOther = \"https://www.cloudflare.com\"\n");
    auto targets=testTargets(fixture);require(targets.size()==3&&targets[0].group=="Discord"&&targets[1].group=="YouTube","Target parsing/dedup failed");require(testTargets(root/L"missing").size()==6,"Fallback targets missing");
    auto full=prepareTestTargets(fixture,"tls",root);require(full.size()==10&&full.back().protocol=="icmp","Expanded TLS/ICMP matrix failed");auto suite=Json::array({Json{{"host","example.com"}},Json{{"host","example.com"}}});auto dpi=dpiTargets(suite,root/L"payload");require(dpi.size()==3&&dpi[2].protocol=="tls13"&&dpi[2].transfer,"DPI protocols/dedup failed");rejects([&]{dpiTargets(Json::array({Json{{"host","user@example.com"}}}),root/L"payload");});require(!testScore(Json::array({Json{{"group","Ping"},{"reachable",true}}})).value("primary",0),"Ping influenced bypass ranking");
    require(transferVerdict(65536,32768,0)=="passed"&&transferVerdict(65536,20480,0)=="inconclusive"&&transferVerdict(65536,0,28)=="suspected_block"&&transferVerdict(0,0,28)=="inconclusive"&&transferVerdict(0,0,35)=="inconclusive"&&transferVerdict(0,0,4)=="unsupported","Transfer test confuses HTTP/TLS errors with proven censorship");require(testReportText(Json::array()).find(L"Результатов пока нет")!=std::wstring::npos&&testReportText(Json{{"message",nullptr}}).find(L"повреждён")!=std::wstring::npos,"Malformed report failed gracefully");
    auto good=[](const char* group,int ms){return Json{{"group",group},{"reachable",true},{"milliseconds",ms}};};
    Json one={{"score",testScore(Json::array({good("Discord",100),good("Other",100)}))}},control={{"score",testScore(Json::array({good("Other",1),good("Other",1),good("Other",1)}))}};
    require(betterTest(one,control),"Control endpoints dominated bypass score");auto fast=one;fast["score"]["milliseconds"]=10;require(betterTest(fast,one)&&!betterTest(one,fast),"Latency tie break failed");
    require(probeTargets(targets,[]{return true;}).empty(),"Cancelled probe made requests");require(probeTargets(targets,[]{throw std::runtime_error("cancel fault");return false;}).empty(),"Cancel callback crashed worker");
    for(size_t i=0;i<128;i++){auto band=strategyPorts(i);require(band.first<=band.last&&band.last<49152,"Test band exceeds reserved range");if(i)require(strategyPorts(i-1).last<band.first,"Test port bands overlap");}rejects([]{strategyPorts(128);});auto isolated=isolatedArguments("\"--wf-tcp=80,443\" \"--wf-udp=443\" \"--filter-tcp=443\" \"--dpi-desync=fake\"",strategyPorts(0));require(isolated.find(L"--wf-tcp=")==std::wstring::npos&&isolated.find(L"--wf-udp=")==std::wstring::npos&&isolated.find(L"--wf-raw=")!=std::wstring::npos&&isolated.find(L"--filter-tcp=443")!=std::wstring::npos,"Isolation retained overlapping filters or lost strategy");
    auto version=inspect(fixture);writeBytes(fixture/L"bin"/L"stun.bin","fake data");writeBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin","old fake");replaceFake(version,"stun.bin",true);require(fileBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin",100)=="fake data"&&fileBytes(fixture/L"bin"/L"ACTIVE_DISCORD_UDP.bin.before-change",100)=="old fake","Fake replacement lost backup");rejects([&]{replaceFake(version,"../winws.exe",true);});
    {auto file=root/L"profiles.json";Profile p{version.id,"general.bat",true,"loaded"};p.gameMode="tcp";p.tcpPorts="27015";savePreset(file,"Игры",p);savePreset(file,"Игры",p);auto profiles=loadLibrary(file);require(profiles.size()==1&&validateChanges(profiles[0]["profile"],Profile{},{version}).tcpPorts=="27015","Preset fields or idempotence failed");auto source=root/L"custom.bat";writeBytes(source,"echo MUST_NOT_EXECUTE\nstart \"test\" \"%BIN%winws.exe\" --wf-tcp=443\n");auto custom=importStrategy(version,source);require(custom.strategies.size()==2&&custom.strategies[1].find("general")==0,"Custom strategy not imported");auto again=importStrategy(version,source);require(again.strategies.size()==2,"Duplicate strategy import");writeBytes(source,"echo bad\nstart \"test\" \"%BIN%winws.exe\" & calc.exe\n");rejects([&]{importStrategy(version,source);});require(inspect(version.path).strategies.size()==2,"Rejected strategy left a file");}
    HANDLE fixtureHandle=nullptr;DWORD fixtureId=0;{
        TestProcess child(fs::absolute(argv[2]),L"");require(child.running(),"Child not running");auto snap=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W p{sizeof(p)};if(Process32FirstW(snap,&p))do{if(p.th32ParentProcessID==GetCurrentProcessId()&&_wcsicmp(p.szExeFile,L"test_process_fixture.exe")==0){fixtureId=p.th32ProcessID;break;}}while(Process32NextW(snap,&p));CloseHandle(snap);require(fixtureId!=0,"Fixture child missing");fixtureHandle=OpenProcess(SYNCHRONIZE,FALSE,fixtureId);require(fixtureHandle!=nullptr,"Fixture handle missing");
    }require(WaitForSingleObject(fixtureHandle,5000)==WAIT_OBJECT_0,"Job left child running");CloseHandle(fixtureHandle);
    {auto log=root/L"captured.log";{TestProcess process(fs::absolute(argv[2]),L"",log);auto deadline=GetTickCount64()+3000;while(GetTickCount64()<deadline&&fileBytes(log,65536).find("fixture stderr")==std::string::npos)Sleep(50);require(fileBytes(log,65536).find("fixture stdout")!=std::string::npos&&fileBytes(log,65536).find("fixture stderr")!=std::string::npos,"Owned process output missing");}require(logTail(log).find("fixture stdout")!=std::string::npos,"Live log reader failed");}
    if(!serviceState().running&&!processNamed(L"winws.exe")&&!processNamed(L"winws2.exe")&&!serviceState().installed){auto session=root/L"session-fixture";fs::copy_file(fs::absolute(argv[2]),fixture/L"bin"/L"winws.exe",fs::copy_options::overwrite_existing);Store store(session/L"settings.json");auto state=store.importVersion(fixture,0);state.profile.strategy="general.bat";store.save(state,state.revision);std::string failure;std::thread worker([&]{try{runSession(session/L"settings.json",GetCurrentProcessId(),false,session/L"runtime");}catch(const std::exception& e){failure=e.what();}});auto deadline=GetTickCount64()+10000;Json status;while(GetTickCount64()<deadline){status=runtimeState(session/L"settings.json");if(!status.empty())break;Sleep(50);}writeBytes(session/L"runtime-stop.flag","");worker.join();require(failure.empty()&&!status.empty()&&runtimeState(session/L"settings.json").empty(),"Session startup/owned stop failed");require(logTail(fs::path(wide(status["log"]))).find("fixture stdout")!=std::string::npos,"Session log missing");std::cout<<"PASS: real owned fixture session, live status, log and stop cleanup (no network engine)\n";}
    {TestStartupGate gate(22);std::atomic<int> alive{0},observed{0};std::vector<std::thread> workers;std::vector<int> snapshots(22);for(size_t i=0;i<22;i++)workers.emplace_back([&,i]{TestProcess child(fs::absolute(argv[2]),L"");alive++;gate.arrive([]{return false;});snapshots[i]=alive.load();observed++;while(observed<22)Sleep(1);alive--;});for(auto& worker:workers)worker.join();for(auto count:snapshots)require(count==22,"Not all strategy fixtures alive at the measurement barrier");std::cout<<"PASS: all 22 owned processes alive together before measurements\n";}
    require(testReportText(Json::object()).find(L"Результатов пока нет")!=std::wstring::npos&&testReportText(Json()).find(L"Результатов пока нет")!=std::wstring::npos,"Empty report rendering failed");Json report={{"message","fixture"},{"results",Json::array()},{"best",nullptr}};require(testReportText(report).find(L"fixture")!=std::wstring::npos,"Report rendering failed");
    auto existing=serviceState();if(existing.installed&&!existing.owned){auto config=root/L"foreign-service-guard"/L"settings.json";fs::create_directories(config.parent_path());runStrategyTests(config,true,GetCurrentProcessId());auto protectedReport=Json::parse(fileBytes(config.parent_path()/L"test-report.json",65536));require(protectedReport.contains("error")&&protectedReport["results"].empty(),"Foreign service not rejected");auto after=serviceState();require(after.binary==existing.binary&&after.running==existing.running&&after.owned==existing.owned,"Foreign service changed");std::cout<<"PASS: existing foreign service rejected without changing its state\n";}
    if(argc==4&&std::wstring(argv[3])==L"--live"){auto rows=probeTargets(testTargets(root/L"missing"),[]{return false;});require(rows.size()==6,"Live probe missing results");for(auto& row:rows)std::cout<<row["name"]<<": TLS "<<row["reachable"]<<", HTTP "<<row["status"]<<", error "<<row["error"]<<"\n";writeJsonAtomic(root/L"live-report.json",{{"targets",rows}});
        std::vector<std::thread> workers;std::vector<Json> bound(3);for(size_t i=0;i<3;i++)workers.emplace_back([&,i]{bound[i]=probeBoundTargets({targets[0],targets[1],targets[2]},strategyPorts(i),[]{return false;});});for(auto& worker:workers)worker.join();int successful=0;for(size_t i=0;i<bound.size();i++)for(auto& row:bound[i]){std::cout<<"Band "<<i<<": "<<row.dump()<<"\n";require(!row.value("isolation_error",false),"Curl escaped local port range");if(row.value("reachable",false)){successful++;auto port=row.at("local_port").get<unsigned>();require(port>=strategyPorts(i).first&&port<=strategyPorts(i).last,"Wrong local port");}}require(successful>0,"No live bound probes succeeded");writeJsonAtomic(root/L"bound-report.json",bound);
    }
    if(argc==4&&std::wstring(argv[3])==L"--live"){auto extended=probeBoundTargets(expandedTargets({targets[0]}),strategyPorts(3),[]{return false;});require(extended.size()==3,"Missing TLS variants");auto suite=prepareTestTargets(fixture,"dpi",root);require(suite.size()>=3,"DPI suite empty");auto transfer=probeBoundTargets({suite[0],suite[1],suite[2]},strategyPorts(4),[]{return false;});require(transfer.size()==3,"DPI probes missing");auto ping=probePing({"Cloudflare DNS","1.1.1.1","Ping","icmp"});std::cout<<"TLS variants: "<<extended.dump()<<"\nDPI anonymous transfer: "<<transfer.dump()<<"\nICMP: "<<ping.dump()<<"\n";writeJsonAtomic(root/L"extended-live-report.json",{{"tls",extended},{"dpi",transfer},{"ping",ping}});}
    std::cout<<"PASS: schema migration/backup, hosts preservation, IPSet modes, presets/custom strategy, TLS/DPI/ICMP, ranking, cancellation, fake backups, process logs and owned process cleanup\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
