#pragma once
#include "maintenance.hpp"
inline void replaceBytes(const fs::path& file,const std::string& bytes){auto temp=fs::path(file.wstring()+L".tmp");writeBytes(temp,bytes);if(!MoveFileExW(temp.c_str(),file.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw std::runtime_error("Не удалось сохранить файл. Исходный файл сохранён.");}
inline bool validAddress(const std::string& text){using Parse=int(WINAPI*)(int,const wchar_t*,void*);static HMODULE library=LoadLibraryExW(L"ws2_32.dll",nullptr,LOAD_LIBRARY_SEARCH_SYSTEM32);auto parse=library?(Parse)GetProcAddress(library,"InetPtonW"):nullptr;unsigned char address[16];return parse&&(parse(2,wide(text).c_str(),address)==1||parse(23,wide(text).c_str(),address)==1);}
inline bool validDomain(const std::string& s){return !s.empty()&&s.size()<=253&&s.front()!='.'&&s.back()!='.'&&s.find("..") == std::string::npos&&std::all_of(s.begin(),s.end(),[](unsigned char c){return (c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='-'||c=='.';});}
inline std::string checkedIpSet(const std::string& bytes){std::istringstream input(bytes);std::string line,result;size_t count=0;while(std::getline(input,line)){line=trim(line);if(line.empty()||line[0]=='#')continue;auto slash=line.find('/');auto ip=line.substr(0,slash);if(!validAddress(ip))throw std::runtime_error("В загруженном IP-списке некорректный адрес.");if(slash!=std::string::npos){auto mask=line.substr(slash+1);if(mask.empty()||mask.size()>3||mask.find_first_not_of("0123456789")!=std::string::npos||std::stoul(mask)>(ip.find(':')==std::string::npos?32:128))throw std::runtime_error("Некорректная маска IP-списка.");}result+=line+"\n";count++;}if(!count)throw std::runtime_error("Загруженный IP-список пуст.");return result;}
inline void updateIpSet(const fs::path& root,const Profile& profile,const std::string& bytes){auto data=checkedIpSet(bytes);auto lists=root/L"lists",file=lists/L"ipset-all.txt",saved=lists/L"ipset-all.txt.backup";auto old=fs::exists(saved)?saved:file;if(fs::exists(old))fs::copy_file(old,lists/L"ipset-all.txt.before-update",fs::copy_options::overwrite_existing);replaceBytes(saved,data);replaceBytes(file,profile.ipset=="loaded"?data:profile.ipset=="any"?"":"203.0.113.113/32\n");}
inline Json loadLibrary(const fs::path& file){if(!fs::exists(file))return Json::array();auto j=Json::parse(fileBytes(file,1024*1024));if(!j.is_array()||j.size()>100)throw std::runtime_error("Библиотека профилей повреждена. Исходный файл сохранён.");for(auto& item:j)if(!item.is_object()||!item.contains("name")||!item["name"].is_string()||!item.contains("profile")||!item["profile"].is_object())throw std::runtime_error("Некорректная библиотека профилей.");return j;}
inline void savePreset(const fs::path& file,const std::string& name,const Profile& p){if(trim(name).empty()||name.size()>200)throw std::runtime_error("Введите название профиля (до 200 байт).");auto all=loadLibrary(file);auto entry=std::find_if(all.begin(),all.end(),[&](auto& row){return row["name"]==name;});Json row={{"name",name},{"profile",profileJson(p)}};if(entry==all.end()){if(all.size()>=100)throw std::runtime_error("Сохранено слишком много профилей.");all.push_back(row);}else *entry=row;writeJsonAtomic(file,all);}
inline Install importStrategy(const Install& version,const fs::path& source){auto bytes=fileBytes(source,256*1024);auto name="general (user-"+sha256(bytes).substr(0,12)+").bat";auto candidate=version;candidate.strategies.push_back(name);auto path=version.path/wide(name);bool existed=fs::exists(path);if(existed&&fileBytes(path,256*1024)!=bytes)throw std::runtime_error("Имя стратегии уже занято.");if(!existed)writeBytes(path,bytes);try{Profile p{version.id,name,false,"loaded"};strategyArguments(candidate,p);}catch(...){if(!existed)fs::remove(path);throw;}auto updated=inspect(version.path);updated.id=version.id;return updated;}
inline const std::string HOSTS_BEGIN="# BEGIN ZapretGUI Flowseal\r\n",HOSTS_END="# END ZapretGUI Flowseal\r\n";
inline std::string withoutManagedHosts(const std::string& input){auto bytes=input;auto begin=bytes.find("# BEGIN ZapretGUI Flowseal"),end=bytes.find("# END ZapretGUI Flowseal");if(begin==std::string::npos&&end==std::string::npos)return bytes;if(begin==std::string::npos||end==std::string::npos||end<begin||(begin&&bytes[begin-1]!='\n')||bytes.find("# BEGIN ZapretGUI Flowseal",begin+1)!=std::string::npos||bytes.find("# END ZapretGUI Flowseal",end+1)!=std::string::npos)throw std::runtime_error("Блок GUI в hosts повреждён. Файл сохранён.");auto tail=bytes.find('\n',end);bytes.erase(begin,tail==std::string::npos?std::string::npos:tail+1-begin);return bytes;}
inline std::vector<std::pair<std::string,std::string>> hostRows(const std::string& bytes,bool strict){std::vector<std::pair<std::string,std::string>> rows;std::istringstream input(bytes);std::string line;while(std::getline(input,line)){line=trim(line.substr(0,line.find('#')));if(line.empty())continue;std::istringstream fields(line);std::string ip,host;fields>>ip;bool valid=validAddress(ip),found=false;while(fields>>host){found=true;if(valid&&validDomain(host))rows.emplace_back(ip,lowerAscii(host));else if(strict)throw std::runtime_error("Некорректная запись hosts.");}if(strict&&(!valid||!found))throw std::runtime_error("Некорректная запись hosts.");}return rows;}
inline std::string mergeHosts(const std::string& original,const std::string& downloaded){auto base=withoutManagedHosts(original);auto rows=hostRows(downloaded,true);if(rows.empty()||rows.size()>2000)throw std::runtime_error("Пустой или слишком большой список hosts.");auto own=hostRows(base,false);for(auto& row:rows)if(std::any_of(own.begin(),own.end(),[&](auto& item){return item.second==row.second;}))throw std::runtime_error("В hosts уже есть ваша запись для "+row.second+". Уберите её вручную перед применением списка.");if(!base.empty()&&base.back()!='\n')base+="\r\n";base+=HOSTS_BEGIN;for(auto& row:rows)base+=row.first+" "+row.second+"\r\n";return base+HOSTS_END;}
inline fs::path systemHosts(){return fs::path(systemExe(L"drivers\\etc\\hosts"));}
inline void changeHosts(const fs::path& file,const std::string& downloaded,bool remove){auto attributes=GetFileAttributesW(file.c_str());if(attributes==INVALID_FILE_ATTRIBUTES||attributes&(FILE_ATTRIBUTE_REPARSE_POINT|FILE_ATTRIBUTE_READONLY))throw std::runtime_error("Файл hosts недоступен, защищён от записи или перенаправлен. Он сохранён.");auto original=fileBytes(file,1024*1024);auto next=remove?withoutManagedHosts(original):mergeHosts(original,downloaded);if(next==original)return;static std::atomic<unsigned> sequence{0};auto backup=fs::path(file.wstring()+L".before-ZapretGUI-"+std::to_wstring(GetTickCount64())+L"-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(sequence++));if(!CopyFileW(file.c_str(),backup.c_str(),TRUE))throw std::runtime_error("Не удалось создать резервную копию hosts.");auto temp=fs::path(file.wstring()+L".ZapretGUI.tmp");writeBytes(temp,next);DWORD needed=0;GetFileSecurityW(file.c_str(),DACL_SECURITY_INFORMATION,nullptr,0,&needed);std::vector<BYTE> security(needed);if(!needed||!GetFileSecurityW(file.c_str(),DACL_SECURITY_INFORMATION,(PSECURITY_DESCRIPTOR)security.data(),needed,&needed)||!SetFileSecurityW(temp.c_str(),DACL_SECURITY_INFORMATION,(PSECURITY_DESCRIPTOR)security.data()))throw std::runtime_error("Не удалось сохранить права доступа hosts. Исходный файл сохранён.");if(!ReplaceFileW(file.c_str(),temp.c_str(),nullptr,REPLACEFILE_IGNORE_MERGE_ERRORS,nullptr,nullptr))throw std::runtime_error("Не удалось заменить hosts. Исходный файл сохранён.");}
struct UiPreferences {bool tray=false,updates=true,session=false,verbose=false;};
inline UiPreferences readPreferences(const fs::path& file){if(!fs::exists(file))return {};auto j=Json::parse(fileBytes(file,8192));return {j.value("tray",false),j.value("updates",true),j.value("session",false),j.value("verbose",false)};}
inline void savePreferences(const fs::path& file,const UiPreferences& p){writeJsonAtomic(file,{{"tray",p.tray},{"updates",p.updates},{"session",p.session},{"verbose",p.verbose}});}
