#pragma once
#include "testing.hpp"
inline fs::path roamingFolder(){PWSTR p=nullptr;if(FAILED(SHGetKnownFolderPath(FOLDERID_RoamingAppData,0,nullptr,&p)))throw std::runtime_error("AppData недоступна.");fs::path folder(p);CoTaskMemFree(p);return folder;}
inline std::vector<std::string> fakeFiles(const Install& v){std::vector<std::string> out;for(auto& f:fs::directory_iterator(v.path/L"bin"))if(f.is_regular_file()&&f.path().extension()==L".bin"&&f.path().filename().wstring().rfind(L"ACTIVE_",0)!=0)out.push_back(utf8(f.path().filename().wstring()));std::sort(out.begin(),out.end());return out;}
inline void replaceFake(const Install& v,const std::string& filename,bool discord){auto all=fakeFiles(v);if(std::find(all.begin(),all.end(),filename)==all.end())throw std::runtime_error("Выберите файл из установленной версии.");auto source=v.path/L"bin"/wide(filename),target=v.path/L"bin"/(discord?L"ACTIVE_DISCORD_UDP.bin":L"ACTIVE_GAME_UDP.bin");auto bytes=fileBytes(source,1024*1024);if(bytes.empty())throw std::runtime_error("Файл пуст.");if(fs::exists(target))fs::copy_file(target,fs::path(target.wstring()+L".before-change"),fs::copy_options::overwrite_existing);auto tmp=fs::path(target.wstring()+L".tmp");writeBytes(tmp,bytes);if(!MoveFileExW(tmp.c_str(),target.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw std::runtime_error("Не удалось заменить файл.");}
inline int backupDiscordCache(){if(processNamed(L"Discord.exe"))throw std::runtime_error("Сначала полностью закройте Discord, включая значок в трее, затем повторите.");auto roaming=fs::weakly_canonical(roamingFolder());int count=0;for(auto app:{L"discord",L"discordcanary",L"discordptb"})for(auto name:{L"Cache",L"Code Cache",L"GPUCache"}){
    auto original=roaming/app/name;if(!fs::exists(original))continue;auto parent=fs::weakly_canonical(original.parent_path());if(parent.parent_path()!=roaming||(GetFileAttributesW(original.c_str())&FILE_ATTRIBUTE_REPARSE_POINT))throw std::runtime_error("Папка кэша перенаправлена. Она сохранена без изменений.");auto backup=fs::path(original.wstring()+L".zapret-backup-"+std::to_wstring(GetTickCount64()));if(!MoveFileExW(original.c_str(),backup.c_str(),0))throw std::runtime_error("Не удалось перенести кэш. Убедитесь, что Discord закрыт.");count++;
}return count;}
inline std::wstring systemDiagnostics(){
    std::wstring text;auto scm=OpenSCManagerW(nullptr,nullptr,SC_MANAGER_CONNECT|SC_MANAGER_ENUMERATE_SERVICE);if(scm){auto bfe=OpenServiceW(scm,L"BFE",SERVICE_QUERY_STATUS);SERVICE_STATUS status{};if(bfe){text+=QueryServiceStatus(bfe,&status)&&status.dwCurrentState==SERVICE_RUNNING?L"Базовая фильтрация Windows (BFE): работает\r\n":L"BFE остановлена: драйверу обхода нужна эта служба\r\n";CloseServiceHandle(bfe);}else text+=L"BFE: статус недоступен\r\n";
        DWORD needed=0,count=0,resume=0;EnumServicesStatusExW(scm,SC_ENUM_PROCESS_INFO,SERVICE_WIN32|SERVICE_DRIVER,SERVICE_ACTIVE,nullptr,0,&needed,&count,&resume,nullptr);if(needed&&needed<2*1024*1024){std::vector<BYTE> buffer(needed);resume=0;if(EnumServicesStatusExW(scm,SC_ENUM_PROCESS_INFO,SERVICE_WIN32|SERVICE_DRIVER,SERVICE_ACTIVE,buffer.data(),needed,&needed,&count,&resume,nullptr)){auto list=(ENUM_SERVICE_STATUS_PROCESSW*)buffer.data();for(DWORD i=0;i<count;i++){auto name=lowerAscii(utf8(std::wstring(list[i].lpServiceName)+L" "+list[i].lpDisplayName));bool suspect=false;for(auto marker:{"killer","smartbyte","tracsrvwrapper","epwd","intel connectivity","adguard","vpn","windivert"})if(name.find(marker)!=std::string::npos)suspect=true;if(suspect)text+=L"Работает: "+std::wstring(list[i].lpDisplayName)+L" (возможное влияние на сеть)\r\n";}}}CloseServiceHandle(scm);
    }else text+=L"Системные службы: статус недоступен\r\n";
    for(auto name:{L"AdguardSvc.exe",L"goodbyedpi.exe",L"winws2.exe"})if(processNamed(name))text+=L"Обнаружена программа: "+std::wstring(name)+L". Может влиять на результат тестов.\r\n";
    HKEY key=nullptr;if(RegOpenKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings",0,KEY_READ,&key)==ERROR_SUCCESS){DWORD enabled=0,size=sizeof(enabled),type=0;if(RegQueryValueExW(key,L"ProxyEnable",nullptr,&type,(BYTE*)&enabled,&size)==ERROR_SUCCESS&&type==REG_DWORD&&enabled)text+=L"В Windows включён прокси. Проверки GUI идут напрямую; VPN может влиять на них.\r\n";RegCloseKey(key);}
    auto hosts=fs::path(systemExe(L"drivers\\etc\\hosts"));if(fs::exists(hosts))try{std::istringstream input(fileBytes(hosts,1024*1024));std::string line;while(std::getline(input,line)){line=lowerAscii(trim(line));if(!line.empty()&&line[0]!='#'&&(line.find("youtube.com")!=std::string::npos||line.find("youtu.be")!=std::string::npos||line.find("discord.com")!=std::string::npos)){text+=L"В hosts есть записи YouTube/Discord: они могут менять адреса сайтов.\r\n";break;}}}catch(...){text+=L"Не удалось прочитать hosts.\r\n";}
    return text;
}
